version: '3'

services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile-postgres
    privileged: true
    ports:
      - 5432:5432

  mongo:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile-mongo
    privileged: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=be
      - MONGO_INITDB_ROOT_PASSWORD=be
    ports:
      - 27017:27017
#    volumes:
#      - mongodbdata:/data/db
    restart: unless-stopped

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile-redis
    privileged: true
    ports:
      - 6379:6379

#volumes:
#    mongodbdata:


#  apiserver:
#    container_name: apiserver
#    build:
#      context: ./apiserver
#      dockerfile: Dockerfile-apiserver
#    privileged: true
#    entrypoint: /bin/bash
#    command: -c "node server.js"
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres